# Generated by Django 3.1.3 on 2020-11-12 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=200)),
                ('req_ch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('grad_year', models.IntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('ch_taken', models.IntegerField(default=0)),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.major')),
            ],
        ),
    ]
