# Generated by Django 3.1.3 on 2020-11-12 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20201112_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentCourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('semester', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'unique_together': {('roll_number', 'course')},
            },
        ),
        migrations.CreateModel(
            name='preReqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('preReq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prereqcourse', to='student.course')),
            ],
            options={
                'unique_together': {('course', 'preReq')},
            },
        ),
        migrations.CreateModel(
            name='antiReqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiReq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antireqcourse', to='student.course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
            ],
            options={
                'unique_together': {('course', 'antiReq')},
            },
        ),
    ]
