# Generated by Django 3.1.3 on 2020-11-12 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_antireqs_prereqs_studentcourseinfo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='antireqs',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='antireqs',
            name='antiReq',
        ),
        migrations.RemoveField(
            model_name='antireqs',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='major',
        ),
        migrations.RemoveField(
            model_name='majorcourses',
            name='course',
        ),
        migrations.RemoveField(
            model_name='majorcourses',
            name='major',
        ),
        migrations.RemoveField(
            model_name='minorcourses',
            name='course',
        ),
        migrations.RemoveField(
            model_name='minorcourses',
            name='minor',
        ),
        migrations.AlterUniqueTogether(
            name='prereqs',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='prereqs',
            name='course',
        ),
        migrations.RemoveField(
            model_name='prereqs',
            name='preReq',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.AlterUniqueTogether(
            name='studentcourseinfo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentcourseinfo',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourseinfo',
            name='roll_number',
        ),
        migrations.DeleteModel(
            name='Advisor',
        ),
        migrations.DeleteModel(
            name='antiReqs',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='majorCourses',
        ),
        migrations.DeleteModel(
            name='Minor',
        ),
        migrations.DeleteModel(
            name='minorCourses',
        ),
        migrations.DeleteModel(
            name='preReqs',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='studentCourseInfo',
        ),
    ]
